run a test

diff --git a/.github/workflows/test-acceptance.yml b/.github/workflows/test-acceptance.yml
--- a/.github/workflows/test-acceptance.yml
+++ b/.github/workflows/test-acceptance.yml
@@ -140,7 +140,63 @@ jobs:
         run: |
           go install github.com/josephburnett/jd@latest
 
-      - name: service start
+      - name: Start steamipipe service
         run: |
           steampipe service start
+
+      - name: Run Test Suite
+        id: run-test-suite
+        timeout-minutes: 15
+        continue-on-error: true
+        run: |
+          chmod +x $GITHUB_WORKSPACE/powerpipe/tests/acceptance/run.sh
+          $GITHUB_WORKSPACE/powerpipe/tests/acceptance/run.sh ${{ matrix.test_block }}.bats
+          echo "exit_code=$(echo $?)" >> $GITHUB_OUTPUT
+          echo ">> here"
+
+      - name: Save Test Suite Logs
+        uses: actions/upload-artifact@v3
+        with:
+          name: test-logs-${{ matrix.test_block }}-${{ matrix.platform }}
+          path: ~/.powerpipe/logs
+          if-no-files-found: error
+
+      # This job checks whether the test suite has passed or not.
+      # Since the exit_code is set only when the bats test suite pass,
+      # we have added the if-conditional block
+      - name: Check Test Passed/Failed
+        if: ${{ success() }}
+        continue-on-error: false
+        run: |
+          if [ ${{ steps.run-test-suite.outputs.exit_code }} -eq 0 ]; then
+            exit 0
+          else
+            exit 1
+          fi
+
+      - name: Stop steampipe service
+        run: |
           steampipe service stop
+
+  cleanup:
+    # let's clean up the artifacts.
+    # incase this step isn't reached,
+    # artifacts automatically expire after 90 days anyway
+    # refer:
+    #   https://docs.github.com/en/actions/configuring-and-managing-workflows/persisting-workflow-data-using-artifacts#downloading-and-deleting-artifacts-after-a-workflow-run-is-complete
+    name: Clean Up Artifacts
+    needs: acceptance_test
+    if: ${{ needs.acceptance_test.result == 'success' }}
+    runs-on: ubuntu-latest
+    steps:
+      - name: Clean up Linux Build
+        uses: geekyeggo/delete-artifact@v4
+        with:
+          name: build-artifact-linux
+          failOnError: true
+
+      - name: Clean up Darwin Build
+        uses: geekyeggo/delete-artifact@v4
+        with:
+          name: build-artifact-darwin
+          failOnError: true
